[profile.default]
#auto_detect_solc = false
solc-version = "0.8.24"
evm_version = 'london'
optimizer = true
optimizer_runs = 800
cache = true
src = "src"
out = "out"
libs = ["lib"]
ffi = true
remappings = [
  'ds-test/=lib/forge-std/lib/ds-test/src/',
  'forge-std/=lib/forge-std/src/',
  '@thirdweb-dev/dynamic-contracts/=lib/dynamic-contracts/src/',
  '@murky/=lib/murky/src/',
  '@thirdweb-dev/dynamic-contracts/=node_modules/@thirdweb-dev/dynamic-contracts/src/'
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
