[profile.default]
#auto_detect_solc = false
solc-version = "0.8.17"
evm_version = 'london'
optimizer = true
optimizer_runs = 800
cache = true
src = "src"
out = "out"
libs = ["lib"]
ffi = true

remappings = [
  'ds-test/=lib/forge-std/lib/ds-test/src/',
  'forge-std/=lib/forge-std/src/',
  '@murky/=lib/murky/src/',
  '@openzeppelin/contracts-upgradeable/=lib/zora-721-contracts/lib/openzeppelin-contracts-upgradeable/contracts/',
  '@openzeppelin/=lib/openzeppelin-contracts/',
  '@manifoldxyz/creator-core-extensions-solidity/=lib/creator-core-extensions-solidity/packages/',
  '@manifoldxyz/creator-core-solidity/contracts/=lib/creator-core-solidity/contracts/',
  '@manifoldxyz/libraries-solidity/contracts/=lib/creator-core-solidity/lib/libraries-solidity/contracts/',
  '@zoralabs/protocol-rewards/src/=lib/protocol-rewards/src/',
  '@zoralabs/zora-721-contracts/=lib/zora-721-contracts/src/',
  '@thirdweb-dev/dynamic-contracts/=lib/dynamic-contracts/src/',
  'erc721a-upgradeable/=lib/erc721a-upgradeable/contracts/',
  '@contracts-next/=lib/thirdweb-contracts-next/src/',
]
